### ISSUE TITLE
Doesn't run clang from CWD!

### ISSUE THREAD

**Issue by jgiokas** [AtomLinter/linter-clang#102]
Hi,

Suppose we have project a directory/file hierarchy as following
project
- test.cpp
- include/
  - test.hpp

test.cpp includes test.hpp

Start atom from the 'project' directory.
If in the linter-clang include path option we give "include" (without quotes), the linter complains that it can not find the test.hpp.
However, if you run manually whatever the linter-clang runs it's fine no errors.
I've found after some digging that the cwd for the clang command from the clang-linter is the root (/) directory instead of the project directory. So if you give the absolute path of the include directory is fine. But this is wrong IMHO, the include paths given to the linter-clang settings must be relative to the cwd.

**Comment by k2b6s9j** [comment]
Yes. I agree that the CWD should be set properly. Simple oversight on my part during the rewrite of this package.

**Comment by jgiokas** [comment]
Cool. It would also be nice to add again the option of a hidden file in the cwd which holds the include paths like the .linter-clang-includes because you have to isolate the include paths of the project you are working on instead of having global include paths which you have to change every time you open another project.

Thanks in advance.

**Comment by k2b6s9j** [comment]
Use .clang_complete rather.
