### ISSUE TITLE
C++11 support doesn't work, when set in default flags

### ISSUE THREAD

**Issue by zinzila** [AtomLinter/linter-clang#105]
If one sets default C++ flags as "-Wall -std=c++11" C++ 11 is not enabled. 
Reason is, default options are appended as single string, and are parsed wrongly, as a single option

Here is output of clang execution:

 "/usr/lib/llvm-3.6/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -main-file-name board.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.25 -v -dwarf-column-info -resource-dir /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0 -I . -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include -internal-externc-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /home/z/projects/drw -ferror-limit 0 -fmessage-length 0 -fdiagnostics-print-source-range-info -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fno-caret-diagnostics -fno-diagnostics-fixit-info -fdiagnostics-show-option -x c++ /home/z/projects/drw/board.cpp
**warning: unknown warning option '-Wall -std=c++11' [-Wunknown-warning-option]**

**Comment by zhipeng-jia** [comment]
#104 solves this problem

**Comment by k2b6s9j** [comment]
The latest version should fix this. If the issue is still occurring please reopen this ticket.
