### ISSUE TITLE
hide when not necessary in status bar

### ISSUE THREAD

**Issue by ScriptorNY** [AtomLinter/linter-clang#107]
Hello,

Would it be possible to deactivate the status bar element : 

![status bar linter](https://imgur.com/ubnRJTV.png)

when it is unnecessary ? For example when I'm in settings, I can still see the element.

Thank you very much in advance :)

**Comment by k2b6s9j** [comment]
Nothing `linter-clang` can do about that. Gotta file an issue at [atom-community/linter](https://github.com/atom-community/linter).

**Comment by ScriptorNY** [comment]
Okay no problem, and thank you for your time :)
