### ISSUE TITLE
OpenMP header file

### ISSUE THREAD

**Issue by gdmsl** [AtomLinter/linter-clang#108]
Hi! I'm using OpenMP for my project written in c++ but I get the error `'omp.h': file not found` but the project compile fine with gcc. I've already added `-fopenmp` in the settings for the CXX Flags with no result. I'm on Archlinux with installed clang 3.6x.

**Comment by k2b6s9j** [comment]
You said you were able to get your project to compile with `gcc` on your system, mind testing if the same is true for `clang`?

**Comment by k2b6s9j** [comment]
Also, since you do have your project working with `gcc`, and if you do have a preference on the C compiler you use for static analysis I recommend [`linter-gcc`](https://github.com/hebaishi/linter-gcc).

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still experiencing this issue feel free to respond to the question above @gdmsl!
