### ISSUE TITLE
Add support for include-what-you-use?

### ISSUE THREAD

**Issue by jbreitbart** [AtomLinter/linter-clang#113]
include-what-you-use is a tool based on clang that can checks include directives if they are really needed and suggests solutions, e.g. move the include from your .hpp file to your .cpp file, because it is only required in your implementation, not the headers.

Do you have any plans to add (optional) support for this tool? Or do you think it should be in its own atom package?

A few links to IWYU:
https://github.com/include-what-you-use/include-what-you-use
http://include-what-you-use.org/

**Comment by kepler0** [comment]
That looks like a great tool! However, support for it is outside of the scope for this package. I would be interested in seeing this integrated with Atom using some other package(s) though.
