### ISSUE TITLE
Handling of spaces after -I in .clang_complete

### ISSUE THREAD

**Issue by LongHairedHacker** [AtomLinter/linter-clang#115]
Hi,
I've noticed some odd behaviour when using a .clang_complete file.

The file contains 2 lines like this:
```
-I include
-I foo/include
```
This results in two entries in the args array, which is passed to exec: `"-I include"` and `"-I foo/include"`.
Clang expects the shell to split the command line at any unescaped space therefore tries to look for includes in `" include"` and `" foo/include"`, which fails since these directories do not exist.

I don't know wether this is intentional in order to avoid implementing an escaping mechanism,
or an actual bug.

In any case this behaviour might be surprising to some people and there should be at least a warning in the readme file.

**Comment by kepler0** [comment]
This is a great change and would love to merge it in, but you have to create a pull request on this repository to do so, not a pull request on your repo.

**Comment by LongHairedHacker** [comment]
D'oh ... I guess I was already half asleep ...

Anyway should be alright now.

**Comment by kepler0** [comment]
Don't even worry about it! We got it in.
