### ISSUE TITLE
Execute clang in the same folder as Makefile

### ISSUE THREAD

**Issue by archi** [AtomLinter/linter-clang#12]
We have a lot of packages with the following dir structure:
package_name/Makefile
package_name/include/package/.h
package_name/src/.cpp
package_name/bin/.{cpp,h}
package_name/tests/
And a project/target consists of a set of these packages in a common folder.

Include paths (relative to package_name/) are ./, ./include and ./../usr/include

atom runs clang in the subfolders, i.e. package_name/src/ for a cpp file. So I added a toggle to figure out where the Makefile is located and run clang there (or fall back to the subfolder if no Makefile can be located).

If there is interest in this, I will branch and create a pull request (might actually be a duplicate of Issue #10?)

**Comment by Snake231088** [comment]
I meged all pull requests, if it works please close this issues!
Thanks

**Comment by m-bra** [comment]
@Snake231088 this issue is solved, please close.
