### ISSUE TITLE
support clang recursive include paths

### ISSUE THREAD

**Issue by dh1tw** [AtomLinter/linter-clang#127]
Hi,

would it be possible to support the recursive search for clang includes? 

This can usually be done by including /*\* at the end of the include.

e.g.: 
-I/Users/user/.platformio/packages/framework-mbed/variant/K64F/**

Thanks!

**Comment by Arcanemagus** [comment]
There is nothing stopping you from entering paths like that in the "Clang Include Paths" setting, maybe it didn't exist when this issue was filed? In any case it should work just fine now.

**Comment by wickles** [comment]
This does not work for me. Using `/usr/local/include/c++/7.3.0` it's fine but using `/usr/local/include/c++/*` it gives me an error, `'iostream' file not found`.
