### ISSUE TITLE
Can't update to the latest version

### ISSUE THREAD

**Issue by trainto** [AtomLinter/linter-clang#133]
When I check the releases page, the latest version is 3.3.5.
But if I try to update from ATOM, it says there is no updates for it. My ATOM has 3.3.0 linter-clang.
Even if I remove the linter-clang and re-install it, it still installs 3.3.0.
Do I need to update it manually?

**Comment by Arcanemagus** [comment]
Looks like for some reason the last few releases haven't been pushed up to `apm`, any idea why @kepler0?

**Comment by kepler0** [comment]
No idea. Just broke semver and pushed a minor to see if it worked. Mind checking @trainto?

**Comment by trainto** [comment]
@kepler0 I'm sorry but I don't understand "broke semver and pushed a minor". Do you mean modify the version code manually?(like package.json)
If you let me know more details to check, I'll check.

**Comment by trainto** [comment]
Now It seems work properly to update 3.4.0

**Comment by kepler0** [comment]
@trainto I just mean that I broke the [Semantic Versioning](http://semver.org/) standard in this.
