### ISSUE TITLE
Not Detecting C++ Files.

### ISSUE THREAD

**Issue by AV-IO** [AtomLinter/linter-clang#135]
This package seems to not be looking at C++ files, it is however properly linting C files.

![2016-01-25_21-58-59](https://cloud.githubusercontent.com/assets/12161056/12572906/65bd3746-c3af-11e5-887a-872fa96f9a1c.png)

As you can see I used many c++ file types, none of which were linted by the package.

**Currently running:**
* Windows 10
* Atom 1.4.1 (also in 1.4.0)
* linter 1.11.3
* linter-clang 3.4.0

Settings  | Changed to
-------------: | :-------------
Clang Default Cpp Flags:  | -Wall -std=c++17 (has also been tested with -std=c++14)
Clang Include Paths  | C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0

**Comment by Arcanemagus** [comment]
This package [lists itself](https://github.com/AtomLinter/linter-clang/blob/v3.4.0/lib/main.js#L57) as being compatible with the following scopes:

* `source.c`
* `source.cpp`
* `source.objc`
* `source.objcpp`

If you run `Editor: Log Cursor Scope` while in one of the files it isn't working on, do you see one of those scopes listed?

**Comment by AV-IO** [comment]
Scopes at Cursor

* source.cpp
* meta.block.c
* meta.block.c
* punctuation.section.block.end.c

-----

Could there be any conflicting packages causing this problem?

**Comment by Arcanemagus** [comment]
@AV-IO did you figure out what was going on? From your scope list it should have been working.

**Comment by AV-IO** [comment]
user error

PATH set to old clang version as well as wrong c++ version apparently not supported

**Comment by Arcanemagus** [comment]
Ah, thanks for reporting back :wink:
