### ISSUE TITLE
Usign linter-clang on linux kernel code

### ISSUE THREAD

**Issue by useche** [AtomLinter/linter-clang#144]
I'm trying to use linter-clang to edit the linux kernel code. Unfortunately, it does not seem to be doing anything. It does not print anything in the console either even after I checked the "Verbose Debug" checkbox in the settings.

I'm using the compile_commands.json file.

**Comment by Arcanemagus** [comment]
It looks like the verbose debug option really only sends `--verbose` to `clang`, and enables logging failures to get the `clang_flags`.

Are you still experiencing issues?

**Comment by useche** [comment]
I haven't tried in a while and I'm not using this setup anymore. Maybe lets close and I will reopen if I bump into this again.
