### ISSUE TITLE
Deprecated Call: "The TextEditor constructor is no longer public"

### ISSUE THREAD

**Issue by adrian5** [AtomLinter/linter-clang#145]
> autocomplete-clang (1 deprecation)
> The TextEditor constructor is no longer public.
> To construct a text editor, use atom.workspace.buildTextEdtior(). To check if an object is a text editor, use atom.workspace.isTextEditor(object)

For me the plug-in simply does nothing, and I've tried a lot. Not sure if above issue is the show stopper.

**Comment by keplersj** [comment]
That's for autocomplete-clang, separate from linter-clang.

**Comment by adrian5** [comment]
My apologies, it was late and I got sloppy. In light of my problem to get the linter to work, is there some course of action you can recommend to me; maybe some way to debug?

I looked for a "toggle" to run the linter, that I might have missed, but wasn't able to find one. I assume it's intended to run on its own after saving files, or what's the intended behavior?

**Comment by adrian5** [comment]
I figured it out myself. I needed to install the "linter" plugin separately. I assumed _linter-clang_ would pull in its dependencies automatically.
