### ISSUE TITLE
clang fatal error 'string' file not found

### ISSUE THREAD

**Issue by canxer314** [AtomLinter/linter-clang#151]
``` h++
#ifndef PROCESS_H
#define PROCESS_H

#include <string>
using std::string;

//PCB
class Process
{
public:
        Process( const string, const int, const int, const int );
        ~Process();
};

#endif /* ifndef PROCESS_H */
```

I wrote a small program which include the '.h' file above, and it turns out an error like the titile.
`clang fatal error 'string' file not found`
So I wrote a .clang_complete file like:

``` text
-I/usr/local/bin/../include/c++/v1
-I/usr/local/include
-I/usr/local/bin/../lib/clang/3.8.0/include
-I/usr/include/x86_64-linux-gnu
-I/usr/include
```

and the new error is 

``` text
clang error unknown type name 'class' at line 8 col 1 in process.h
clang error expected ';' after top level declarator at line 8 col 14 in process.h
clang error unknown type name '_LIBCPP_BEGIN_NAMESPACE_STD' at line 96 col 1 in /usr/local/bin/../include/c++/v1/iosfwd
clang error expected ';' after top level declarator at line 98 col 6 in /usr/local/bin/../include/c++/v1/iosfwd
```

**Comment by akappel** [comment]
Is there a difference between `using std::string` and `using namespace std::string`? Not familiar enough with c++ to know if that's valid or not; I've only ever seen `using namespace std;` in my limited experience with the language.

**Comment by Arcanemagus** [comment]
@akappel I'm assuming you already have looked this up long ago, but to answer your question `using std::string` means that `string` will use `std::string` automatically. `using namespace std::string` doesn't actually make any sense, so I'm not sure what it would do. See [here](http://en.cppreference.com/w/cpp/language/namespace) for a quick reference on the topic.

@canxer314 This looks more like a system configuration issue than a problem with this package, were you able to resolve that already?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having issues please provide more information, thanks!
