### ISSUE TITLE
Can't find standard headers in header files

### ISSUE THREAD

**Issue by xiaochuanyu** [AtomLinter/linter-clang#154]
I have the following file "test.h":

```
#ifndef TEST_H
#define TEST_H

#include <iostream>


#endif
```

I get an error saying "'iostream' file not foundat line 4 col 10" from the linter.
Things work properly in cpp files though.
Also, if instead I put `#pragma once` instead of the `ifndef` guard. I observe issue #120 at the same time.
For example:

```
#pragma once

#include <iostream>


#endif
```

I am using version 3.4.4.

**Comment by Arcanemagus** [comment]
It sounds like you will need to configure a [`.clang_complete`](https://github.com/AtomLinter/linter-clang#clang_complete) file to setup your includes.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having issues please provide more information, thanks!
