### ISSUE TITLE
No cursor indication for resize handle on clang message pane

### ISSUE THREAD

**Issue by thehans** [AtomLinter/linter-clang#157]
When hovering over the top edge of the messages pane, I would expect the cursor to change to a "resize arrow" to indicate that I can click drag to resize.

Currently the mouse cursor does change to this arrow, but only after mousedown.  I spent some time hovering my mouse all around to try to figure out how to resize it since I saw no indication when I was in the right spot.

Atom 1.7.4, 
UI Theme: Atom Dark, Syntax Theme: Atom Dark
linter-clang 3.4.4

**Comment by Arcanemagus** [comment]
Please file this on [linter-ui-default](https://github.com/steelbrain/linter-ui-default/issues) as that is where all UI work on `linter` (which provides the interface for `linter-clang`) is being done.
