### ISSUE TITLE
Not handling source encoding

### ISSUE THREAD

**Issue by daltones** [AtomLinter/linter-clang#158]
Warning/error marks appear at wrong positions if the source encoding uses multi-byte chars, probably because returned offsets are in bytes.

``` c
/* UTF-8 double-byte char here: ñ */ foo = bar->baz;
//                                         ~~~    Correct mark on "bar"
//                                          ~~~   But it appears one column ahead
```

Is there any way to tell Clang the source encoding?

**Comment by Arcanemagus** [comment]
Very interesting, this is actually a bug in `clang` itself.

![image](https://cloud.githubusercontent.com/assets/427137/22087165/4f7f836a-dd91-11e6-943e-5e8f8dc5d3a9.png)

Notice how the carets line up properly with the output, and the numbers are correct in the first line (I copied it above just to check), but the line with the symbol the numbers are off by one from what they should be.

I tested this with the following version:
```
clang version 3.9.1 (branches/release_39)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

I'm going to close this as this isn't a bug we can fix here, but I'm sure the LLVM project would appreciate a bug report (if one doesn't already exist).
