### ISSUE TITLE
Failed to spawn command `undefined`

### ISSUE THREAD

**Issue by jplatte** [AtomLinter/linter-clang#16]
Whenever linter-clang tries to process a file since the latest package update (2.9.0), I get the following error in the console:

```
Uncaught BufferedProcessError: Failed to spawn command `undefined`. Make sure `undefined` is installed and on your PATH [/usr/share/atom/resources/app/src/buffered-process.js:96]
(anonymous function) [/usr/share/atom/resources/app/src/buffered-process.js:96]
emit [events.js:107]
ChildProcess._handle.onexit [child_process.js:1070]
(anonymous function) [child_process.js:1142]
_tickCallback [node.js:378]
```

This is independent of what I set "Clang command" and "Clang Plus Plus Command" to in the settings.

**Comment by Ricain** [comment]
Hi all, is there progress?

**Comment by k2b6s9j** [comment]
Yes. I made a patch a while ago and have been waiting for it to be merged.

**Comment by Stephen304** [comment]
Waiting for this. In the meantime, atom-lint is working with clang, though I'd like to have all my linters more consolidated with atomlinter.

**Comment by k2b6s9j** [comment]
You could install the patch yourself locally.

**Comment by Stephen304** [comment]
I've previously had issues with installing plugins manually and them not cleaning up when switching back to the auto installed version, breaking things; I'll just watch this issue and update linter-clang when it's merged.
