### ISSUE TITLE
Linter displays error for <command line>

### ISSUE THREAD

**Issue by akappel** [AtomLinter/linter-clang#163]
Hello,

I've just setup `linter-clang` for Atom on my Windows machine. When I save a `.cpp` file, the linter displays a clang error "expected identifier or '(' at line 6 col 2 in `<command line>`":

![image](https://cloud.githubusercontent.com/assets/3596873/17755963/1180eb08-64ab-11e6-9e0c-fe85a274a967.png)

When I click on the entry, it opens a blank file named <command line>.

The second error is valid since I don't have the proper includes in my `.clang_complete` just yet. Could this have something to do with the way output is being parsed from Clang?

Thanks,
Adrian

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you can provide a reproduction case I would love to update the parser to accommodate it!
