### ISSUE TITLE
Flag for 'glib.h' error.

### ISSUE THREAD

**Issue by UtkarshKunwar** [AtomLinter/linter-clang#165]
The flag for `glib.h` in C, which is `pkg-config --cflags --libs glib-2.0` (from [stackoverflow](http://stackoverflow.com/questions/1146010/why-cant-i-build-a-hello-world-for-glib)) suppresses the `glib.h : file not found.` error but also suppresses all the other errors and warnings as well.

Without flag (clearly that's a warning right there) - 
![screenshot from 2016-08-27 11 34 28](https://cloud.githubusercontent.com/assets/14164924/18025551/5f04058a-6c4a-11e6-8ba7-98a56e9c15c0.png)

Adding the flag - 
![screenshot from 2016-08-27 11 34 47](https://cloud.githubusercontent.com/assets/14164924/18025554/6c67db70-6c4a-11e6-9122-10000a2bebcd.png)

With flag added (The warning has disappeared which should not happen) - 
![screenshot from 2016-08-27 11 34 52](https://cloud.githubusercontent.com/assets/14164924/18025563/fd2f4a26-6c4a-11e6-8762-af30e0ad7a63.png)

**Comment by Arcanemagus** [comment]
Can you reproduce this on the command line? This project is just a wrapper around `clang` so if that flag is causing it to not output anything else, then there isn't anything else that we can show in Atom.

**Comment by Arcanemagus** [comment]
Looked into this in a bit more detail, the configuration you are attempting will _not_ work. If you read the answer it explains that what is really going on here is `pkg-config --cflags --libs glib-2.0` is being executed by the shell and the output placed in the arguments of the first command. Atom is _not_ a shell host like your terminal, you need to specify _exactly_ what you want to run in the settings. So in this case you would need to run that command manually and place the output in the settings.
