### ISSUE TITLE
Run linter inside docker

### ISSUE THREAD

**Issue by tibaes** [AtomLinter/linter-clang#169]
Hi devs,

I use this atom plugin and it is working fine for me.
However I am trying something more advanced: I have a build envirolment based on docker, so when I want to build a project, everything runs inside docker. While coding, it is used the clang from the host machine for linter and autocomplete. What I want to achieve is to use the clang from inside docker to compute the linter and autocomplete, something like: docker run --rm mydevimage g++, instead of the host g++. Is it possible to configure this plugin for this? Or can someone provide me some tips to achieve this goal? 

Thank you :)

**Comment by Arcanemagus** [comment]
First of all, this is `linter-clang`, thus it is using `clang` not `g++`.

Secondly, it might be possible to implement something like that, but it would require quite a bit of work to plumb everything together properly and is really beyond the scope of this project. If you were still interested in implementing this yourself feel free to contact me on Atom's Slack instance if you are having issues getting it working.

**Comment by tibaes** [comment]
I am working to get my entire Atom inside Docker. It is an easier solution comparing to configure each plugin.
