### ISSUE TITLE
Deprecated selector in `linter-clang/styles/linter-clang.less`

### ISSUE THREAD

**Issue by C-Bouthoorn** [AtomLinter/linter-clang#171]
In `linter-clang/styles/linter-clang.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .linter-highlight.fatal-error,
.linter-highlight.fatal-error` => `atom-text-editor.editor .linter-highlight.fatal-error,
.linter-highlight.fatal-error`

* `atom-text-editor::shadow .linter-highlight.fatal-error:not(.line-number),
.linter-highlight.fatal-error:not(.line-number)` => `atom-text-editor.editor .linter-highlight.fatal-error:not(.line-number),
.linter-highlight.fatal-error:not(.line-number)`

* `atom-text-editor::shadow .linter-highlight.fatal-error .linter-gutter,
.linter-highlight.fatal-error .linter-gutter` => `atom-text-editor.editor .linter-highlight.fatal-error .linter-gutter,
.linter-highlight.fatal-error .linter-gutter`

* `atom-text-editor::shadow .linter-highlight.fatal-error .region,
.linter-highlight.fatal-error .region` => `atom-text-editor.editor .linter-highlight.fatal-error .region,
.linter-highlight.fatal-error .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

### Versions
Atom: `1.13.0-beta1`
OS: `Linux 4.4.0-32-generic #51-Ubuntu` (Ubuntu 16.04)
Node: `v6.9.1`
npm: `v4.0.2`
apm: `v1.1.1`

**Comment by erdemalpkaya** [comment]
For my computer That happened after the new version of Atom 1.13.0

**Comment by Foadsf** [comment]
I also have the exact same issue after I updated atom on my mac a couple of days ago. many other packages has been already updated to solve this depreciation issue, but this package is lagging behind.

**Comment by Arcanemagus** [comment]
I'll be releasing an update with the fix to this after a few other things get merged in, depending on how backed up Travis-CI is it should be an hour or two.
