### ISSUE TITLE
Error: spawn clang ENOENT in saving the c++ file

### ISSUE THREAD

**Issue by akshayarise** [AtomLinter/linter-clang#172]
while saving this insertion.cpp file in atom editor in ubuntu 16.04 given below :- 
```js
/*
 * C++ Program to Implement Insertion Sort
 */
#include <iostream>
using namespace std;
int main()
{
    int a[16], i, j, k, temp;
    cout<<"enter the elements\n";
    for (i = 0; i < 16; i++)
    {
        cin>>a[i];
    }
    for (i = 1; i < 16; i++)
    {
        for (j = i; j >= 1; j--)
        {
            if (a[j] < a[j-1])
            {
                temp = a[j];
                a[j] = a[j-1];
                a[j-1] = temp;
            }
            else
                break;
        }
    }
    cout<<"sorted array\n"<<endl;
    for (k = 0; k < 16; k++)
    {
	cout<<a[k]<<endl;
    }
}
```
It is showing this error :- 
```
Error: spawn clang ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98
```

how to resolve this issue ? please help

**Comment by Arcanemagus** [comment]
Is `clang` available on your `$PATH`?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having issues after ensuring `clang` is available on your `$PATH` please try setting the path in the settings and reporting back on the results.

**Comment by erwango** [comment]
Hello

I have the same issue.
Which clang path should I provide? 
PATH=$PATH:/local/home/<my_name>/.atom/packages/linter-clang

I tried to add linter-clang path and $PATH in settings, but did not work better

Thanks for your help !

**Comment by Arcanemagus** [comment]
@erwango Does `which clang` show a path for you?

**Comment by erwango** [comment]
@Arcanemagus :  which clang returns nothing

**Comment by erwango** [comment]
Installed clang, Works fine now.
Sorry, I didn't catch that this was based on outside component.
Thanks for your support
