### ISSUE TITLE
[Package-Deps] Unable to get loaded package 'linter-clang'

### ISSUE THREAD

**Issue by jhh** [AtomLinter/linter-clang#183]
linter-clang stopped finding issues sometime in the recent past and I noticed the above error in the JS console. I've tried reinstalling linter and linter-clang with no luck. I don't see any other reports of this when googling, any suggestions on where else I can look?

**Comment by Arcanemagus** [comment]
Looks like there is a typo in the `package.json` file leading to that being broken (`packages-deps` instead of `package-deps`), I'll get that fixed... but that shouldn't have caused any issue with running the provider as long as you already have Linter installed.
