### ISSUE TITLE
Shows project scoped messages

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-clang#186]
Apparently this provider can show messages for files other than the current, it's likely this is as simple as explicitly specifying this as a `project` scoped provider.

**Comment by steelbrain** [comment]
Here's a screenshot of current behavior

![linter_project](https://cloud.githubusercontent.com/assets/4278113/23727514/2f100aa4-047a-11e7-9bfd-394f185a57bf.png)

**Comment by Arcanemagus** [comment]
Leaving as is, will revisit if this poses a problem and can be reproduced.
