### ISSUE TITLE
Single Line Errors

### ISSUE THREAD

**Issue by nick-prat** [AtomLinter/linter-clang#189]
Only tested with C++, but errors are only displayed with one line now. 
For example if a static_assert fails, the only error displayed is this

```
in instantiation of function template specialization 'Entity<EntityManager<CRender, CLocation> >::addComponent<Scene>' requested here
```

where before it would show multiple lines of information about the error and the build output shows

```
/home/nick/Programming/OpenGL-Project/./src/Entity/entity.hpp:172:9: error: static_assert failed "index() called on invalid type"
        static_assert(contains<comp_t>(), "index() called on invalid type");
        ^             ~~~~~~~~~~~~~~~~~~
/home/nick/Programming/OpenGL-Project/./src/Entity/entity.hpp:68:61: note: in instantiation of function template specialization
      'EntityManager<CRender, CLocation>::index<Scene>' requested here
        auto loc = m_componentIDs[m_entityManager->template index<comp_t>()];
                                                            ^
/home/nick/Programming/OpenGL-Project/src/Scene/scene.cpp:49:9: note: in instantiation of function template specialization 'Entity<EntityManager<CRender, CLocation>
      >::addComponent<Scene>' requested here
    ent.addComponent<Scene>();
```

as you can see, it chops of the beginning of the error, while that is the most important

I originally posted this in the linter repo, but the owner said

> The `excerpt` and `description` have been split into two separate fields now, to get rid of the behavior you're experiencing, you should request the linter provider owner to upgrade their package to Linter v2 API

So I'm guessing this error might belong here? It mostly happens when static_asserts fail

**Comment by Arcanemagus** [comment]
Can you provide a reproduction case for this? Right now the parsing of `clang`'s output is _very_ simplistic and could use some work, but without files to generate test output, I can't do much 😛.

**Comment by nick-prat** [comment]
To replicate this bug, you need a file static_assert.cpp that contains

```
#include "static_assert.hpp"

int main() {
    func<B>();
    return 0;
}
```
and a file static_assert.hpp that contains

```
#ifndef _STATIC_ASSERT_H
#define _STATIC_ASSERT_H

#include <functional>

class A {

};

class B {

};

template<typename T>
void func() {
    static_assert(std::is_same<T,A>::value, "T wasn't A");
}

#endif // STATIC_ASSERT_H
```

the error in atom comes up as
```
in instantiation of function template specialization 'func<B>' requested here
```
but if you use a scan-build on the file it comes up as
```
scan-build: Using '/usr/bin/clang-3.9' for static analysis
In file included from static_assert.cpp:2:
./static_assert.hpp:16:5: error: static_assert failed "T wasn't A"
    static_assert(std::is_same<T,A>::value, "T wasn't A");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~
static_assert.cpp:5:5: note: in instantiation of function template specialization 'func<B>' requested here
    func<B>();
    ^
1 error generated.
scan-build: Removing directory '/tmp/scan-build-2017-03-31-134016-22382-1' because it contains no reports.
scan-build: No bugs found.
```

**Comment by Arcanemagus** [comment]
Thanks! I'll try to reproduce.

**Comment by nick-prat** [comment]
I'm looking at the error a little more now, and I'm pretty sure it's because the error occurs in static_assert.hpp so linter-ui-default won't show it because it's not in the same file. If you change it so the panel shows errors from the whole project it will report it correctly.

**Comment by Arcanemagus** [comment]
Okay, I'm not sure what you mean by "before" since `fno-caret-diagnostics` has been in there from [the beginning](https://github.com/AtomLinter/linter-clang/commit/342afcc9d99b9ab3c27e9199ab24a10d0a0c1c03#diff-92c891a9a26274df2d57fecd97ca8982R12), which is what causes only the single line to be shown.

That being said, the current parser is failing _horribly_ on the output from this which is exactly what I've been looking for an example of. I'll use this to re-write the `clang` output parser so we can get some usable output here.

**Comment by nick-prat** [comment]
I think you're right, I don't think I noticed this issue before v2, as i only started using static_asserts in template code after it was released.

**Comment by Arcanemagus** [comment]
I've got the RegExp written for the parser re-write that should handle this case and a few other edge cases I found in the `clang` documentation, just need to finish plumbing it into the program now.

**Comment by Arcanemagus** [comment]
v4.1.0 is released including these changes. 🎉
