### ISSUE TITLE
[Bug] Underline not show up when error

### ISSUE THREAD

**Issue by ooJerryLeeoo** [AtomLinter/linter-clang#190]
Here's an example:

![screen shot 2017-03-28 at 19 45 02](https://cloud.githubusercontent.com/assets/20783502/24403389/3b6283ac-13ef-11e7-80fb-89116a3e0edd.png)

Update:
Here's `Sublime Text 3` version of the example:

![screen shot 2017-03-28 at 19 49 43](https://cloud.githubusercontent.com/assets/20783502/24403512/ce51602a-13ef-11e7-80b6-6dbcd314dac3.png)

**Comment by Arcanemagus** [comment]
The problem here is that the "range" is simply the imaginary "next" character of the line. I'd more consider this a bug in the SublimeText 3 implementation that they are highlighting a character that doesn't exist.

**Comment by ooJerryLeeoo** [comment]
But some other ide like Xcode doesn't have this problem?

**Comment by ooJerryLeeoo** [comment]
![screen shot 2017-03-29 at 06 46 37](https://cloud.githubusercontent.com/assets/20783502/24430909/97af9cc4-144b-11e7-929b-a48e793606b3.png)

**Comment by Arcanemagus** [comment]
Hmmm, now that's an interesting idea. A different marker for positions that aren't a range.

**Comment by ooJerryLeeoo** [comment]
Here's more example:

`Atom`:

![screen shot 2017-03-29 at 08 47 05](https://cloud.githubusercontent.com/assets/20783502/24433615/8f03c206-145c-11e7-88f2-113b34d9cc5e.png)

`Sublime Text 3`:
![screen shot 2017-03-29 at 08 47 23](https://cloud.githubusercontent.com/assets/20783502/24433629/9c4a2e96-145c-11e7-9605-0598cd3ff1a9.png)

`Xcode`:
![screen shot 2017-03-29 at 08 48 06](https://cloud.githubusercontent.com/assets/20783502/24433644/aecfd57a-145c-11e7-811f-da8fd4892ccc.png)

**Comment by Arcanemagus** [comment]
Hmmm, that looks like a bug, attempting to reproduce.

**Comment by Arcanemagus** [comment]
Wow, this is still using the extremely simplistic `parse` method and not fixing the ranges. I'll get this cleaned up!

**Comment by Arcanemagus** [comment]
Better? 😛

Example 1:
![image](https://cloud.githubusercontent.com/assets/427137/24470244/18ae0ed8-1473-11e7-9fc5-f2015d9a9e94.png)

Example 2:
![image](https://cloud.githubusercontent.com/assets/427137/24470289/47cd3e64-1473-11e7-8090-60c986381fe2.png)

Finishing up a few things before I push the rest of this up.

**Comment by Arcanemagus** [comment]
Looks like this was already requested back in #147 as well.

**Comment by ooJerryLeeoo** [comment]
@Arcanemagus So when to push a new release?

**Comment by Arcanemagus** [comment]
Soon, finishing up one more thing then I'll be pushing out a major version since a setting was changed 😉.

**Comment by ooJerryLeeoo** [comment]
Okay, I got it.

**Comment by Arcanemagus** [comment]
v4.0.0 published 🎉

**Comment by ooJerryLeeoo** [comment]
@Arcanemagus Example 1 and Example 2 are fixed 👍 .
But the example on my first comment still not fixed:

![screen shot 2017-03-31 at 11 13 44](https://cloud.githubusercontent.com/assets/20783502/24534860/218aa926-1603-11e7-80c0-d1bfcf2f0eb6.png)

**Comment by Arcanemagus** [comment]
That's because example 1 and 2 are actual ranges, like I said before the first one has nothing to highlight. That's why I filed https://github.com/steelbrain/linter-ui-default/issues/235.

**Comment by ooJerryLeeoo** [comment]
@Arcanemagus So the problem is `linter` it self ?

**Comment by Arcanemagus** [comment]
The "problem" is that `clang` is telling us there is an issue at the end of the line, but there is no character _after_ the end of the line to highlight so nothing shows other than the gutter marker. That issue is filed to see if there is anything that can be done about it.

What you show for SublimeText 3 is just silly, it seems they are making up an extra character to highlight which is just plain wrong. The Xcode solution of a position marker looks somewhat interesting though.
