### ISSUE TITLE
Linter: Error running clang Error since V4.0.0

### ISSUE THREAD

**Issue by TrovatelliT** [AtomLinter/linter-clang#195]
Hello,

I updated to v4 and and it seems like the plugin can't compile anymore. Each time I save (it try to compile automatically) I've got a strange error message:
```
/Users/Timothy/.atom/packages/linter/lib/linter-registry.js:177 
[Linter] Error running clang Error: Line number (292) greater than maximum line (241)    
    at Object.generateRange (/Users/Timothy/.atom/packages/linter-clang/node_modules/atom-linter/lib/index.js:158:11)
    at Object.<anonymous> (/Users/Timothy/.atom/packages/linter-clang/lib/main.js:190:32)
    at next (<anonymous>)
    at step (/Users/Timothy/.atom/packages/linter-clang/lib/main.js:7:273)
```

Here is a screenshot:
<img width="562" alt="capture d ecran 2017-03-31 a 09 43 36" src="https://cloud.githubusercontent.com/assets/25937253/24541247/edab98b0-15f6-11e7-8b91-24b9cf970eba.png">

**Comment by Thorsten42** [comment]
i also get this error (i am using atom/clang on ubuntu gnome 16.04):
[Linter] Error running clang Error: Column start (9) greater than line length (0) for line 5
    at Object.generateRange (/home/---/.atom/packages/linter-clang/node_modules/atom-linter/lib/index.js:177:11)
    at Object.<anonymous> (/home/---/.atom/packages/linter-clang/lib/main.js:190:32)
    at next (<anonymous>)
    at step (/home/---/.atom/packages/linter-clang/lib/main.js:7:273)

**Comment by eliaskosunen** [comment]
Can confirm, getting a similar error. Atom 1.15.0, linter-clang 4.0.0, linter 2.1.2, Ubuntu 16.04.1 LTS, clang version 3.8.0-2ubuntu4.

> linter-registry.js:144
> [Linter] Error running clang Error: Line number (269) greater than maximum line (91)
>     at Object.generateRange (/home/elias/.atom/packages/linter-clang/node_modules/atom-linter/lib/index.js:158:11)
>     at Object.<anonymous> (/home/elias/.atom/packages/linter-clang/lib/main.js:190:32)
>     at next (<anonymous>)
>     at step (/home/elias/.atom/packages/linter-clang/lib/main.js:7:273)(anonymous function) @ linter-registry.js [sm]:144

**Comment by Arcanemagus** [comment]
Can you create a gist or upload a zip so that I can reproduce this? It's possible that there is a mistake in parsing the initial point from the `clang` output, but it's also possible `clang` is giving out invalid points. v4.0.0 introduces a check for valid points from what `clang` is giving us.

@Thorsten42 yours in particular looks like a common reporting bug I see in linters when this check is first introduced.

**Comment by Viterzgir** [comment]
Also have same problem in archlinux with  Atom 1.15.0, linter-clang 4.0.0, linter 2.1.2
![screenshot-2017-03-31-21 43 58](https://cloud.githubusercontent.com/assets/19819279/24564688/6c900d32-165b-11e7-9b8f-4e45d846ffe4.png)

**Comment by Arcanemagus** [comment]
I've got a parser re-write in the works that should fix most of this, looks like the old regex was basically garbage and only handled the most basic of cases.

**Comment by Arcanemagus** [comment]
v4.1.0 is released including the rewrite for the parser engine which should fix most of these errors. If you are still experiencing problems please file a **new** issue with files to reproduce it with.
