### ISSUE TITLE
[Linter] Error running clang Error

### ISSUE THREAD

**Issue by ooJerryLeeoo** [AtomLinter/linter-clang#201]
Atom keep sending this message:
![image](https://cloud.githubusercontent.com/assets/20783502/24580458/f992abb0-173a-11e7-937c-742819f4ab41.png)

Here's console message:

```
[Linter] Error running clang Error: Line number (141) greater than maximum line (6)(…)

linter-registry.js [sm]:144 
```

UPD:
I've found that atom sending me this message only when autocomplete menu show up, here's an example:

![2017-04-02 00_36_12](https://cloud.githubusercontent.com/assets/20783502/24580553/64138cce-173c-11e7-90a1-0e56dc206a18.gif)

**Comment by NanerLee** [comment]
+1

**Comment by Arcanemagus** [comment]
From what I can see from your GIF the errors occur when you have `print` on a line. When attempting to reproduce this that is when 4 new messages pop up. However... I can't reproduce this on v4.1.0 so I'm guessing this is just one of the many parsing bugs in the versions <v4.1.0. Can you update to a version newer than v4.0.0 and try to reproduce this?

Note that if you are stuck on a version of `clang` less than v4.0.0 then `linter-clang` v4.0.0 and v4.1.0 will be broken for you, however v4.1.1 should be fixed.

**Comment by JayXon** [comment]
I'm using linter-clang 4.1.1 and clang 3.8
```
linter-registry.js [sm]:144 [Linter] Error running clang Error: Column start (9) greater than line length (2) for line 0
    at Object.generateRange (.atom/packages/linter-clang/node_modules/atom-linter/lib/index.js:177:11)
    at Object.<anonymous> (.atom/packages/linter-clang/lib/main.js:181:32)
    at next (<anonymous>)
    at step (.atom/packages/linter-clang/lib/main.js:7:273)(anonymous function) @ linter-registry.js [sm]:144
linter-registry.js [sm]:144 [Linter] Error running clang Error: Column start (9) greater than line length (2) for line 0(…)(anonymous function) @ linter-registry.js [sm]:144
```

**Comment by ooJerryLeeoo** [comment]
Okay, it fix for me after upgrade to v4.1.1.

**Comment by Arcanemagus** [comment]
@JayXon Can you file a new issue and include a set of files to reproduce this with?

**Comment by YoungCapta1n** [comment]
Same issue when using C++ linear algebra library "armadiilo".

**Comment by jagdishrao11** [comment]
yeah i got the solution......make sure you only installed the " linter-clang" package and not any other linter packages......only one linter-clang....                                                    GOOD LUCK

**Comment by jagdishrao11** [comment]
it i fina and  100% working solution...if after uninstall of  other linters packages still coming the same error.....dont worry.......check again clearly.....confirm that you  uninstalled permanently....(only use linter-clang).                                                            THANK YOU.
