### ISSUE TITLE
Linter not working.

### ISSUE THREAD

**Issue by horcrux2301** [AtomLinter/linter-clang#202]
I am trying to make a cpp file and even when I type gibberish the linter shows me no errors.

I have linter(2.1.2), linter-clang(4.1.0) and linter ui-default(1.2.2) installed. I am using MacOS. Can anybody please help me in fixing this?

**Comment by NanerLee** [comment]
+1

**Comment by horcrux2301** [comment]
Someone suggested me to install the version 4.0.0 in another thread and it seems to work fine for now. @NanerLee

**Comment by TrovatelliT** [comment]
Same of me on mac with and in C

**Comment by diegoferigo** [comment]
+1 on Ubuntu 16.10 and v4.1.0

**Comment by Arcanemagus** [comment]
Closing as a duplicate of #199.
