### ISSUE TITLE
Linter-clang does not work

### ISSUE THREAD

**Issue by BreederBai** [AtomLinter/linter-clang#220]
In ardupilot project，Grammar detection does not work.I would like to know if this is the problem I set up, or should the project too much, too many documents.This is my dialogue with @steelbrain https://github.com/steelbrain/linter/issues/1535

**Comment by Arcanemagus** [comment]
If you open Atom's Developer Tools, find the files for this package and place a breakpoint here:

https://github.com/AtomLinter/linter-clang/blob/47ae300f6f19f671c98ada0b377e5c5e54a22279/lib/main.js#L257

Are you seeing expected results in the contents of `output`?

There are two possibilities here:
* It is returning before even running `clang`
* It's failing to parse the results from `clang`

**Comment by BreederBai** [comment]
Excuse me, what tools do I use, place breakpoints? @Arcanemagus

**Comment by Arcanemagus** [comment]
1. View ➡️ Developer ➡️ Toggle Developer Tools ➡️ Sources tab
2. <kbd>Ctrl</kbd> + <kbd>p</kbd> or click here and select "Go to file..." ![image](https://user-images.githubusercontent.com/427137/29933102-4baefc98-8e2b-11e7-8b18-6e3d65559dcb.png)
3. Type `linter-clang` and select the _first_ result, the one that is just `main.js`, not the full path. If you are on a different OS this list is probably cleaner 😛. ![image](https://user-images.githubusercontent.com/427137/29933084-332b11e8-8e2b-11e7-85b4-df2538d9e0af.png)
4. Scroll down to around line 255 and click the line numbers until it lets you select one at the same "level" as `const output = ...`, ideally it should let you select line 257, but it looks like for me that was line 264: ![image](https://user-images.githubusercontent.com/427137/29933241-cdac0862-8e2b-11e7-8a17-e3b842b452f4.png)
5. Trigger a lint by saving a file you expect results on.
6. Type `output` in the Console that should be open on the bottom (or go to the Console tab at the very top). This will show you the raw output that was returned from `clang`.

**Comment by BreederBai** [comment]
Thank you very much for your patience @Arcanemagus. When I open the interface, I see the following situation,four error,two warning
![image](https://user-images.githubusercontent.com/27894314/29958552-d8803ed4-8f25-11e7-8a23-f5810399b956.png)

**Comment by BreederBai** [comment]
When I press the Save button, the screen appears
![image](https://user-images.githubusercontent.com/27894314/29960133-f79ea074-8f2c-11e7-9de4-d61ee383e789.png)

**Comment by BreederBai** [comment]
When I enter in the project, the following debugging information appears
![image](https://user-images.githubusercontent.com/27894314/29960427-236b36d0-8f2e-11e7-9d83-165231d6e04a.png)
Then I press the Save button again,
![image](https://user-images.githubusercontent.com/27894314/29960483-66b5b15e-8f2e-11e7-8c9c-487564fe45a2.png)

**Comment by Arcanemagus** [comment]
@BreederBai Do you have `clang` available on your path? Meaning does `where.exe clang` show a result?

I'm guessing that this is a badly garbled message saying it couldn't find `clang`:
![image](https://user-images.githubusercontent.com/427137/29978196-01429276-8ef5-11e7-9094-eb67fe6554b6.png)

(Also note that one of your other packages is trying to run `grep`, which you don't have on your system.)

**Comment by BreederBai** [comment]
How can I solve this problem? @Arcanemagus

**Comment by Arcanemagus** [comment]
@BreederBai You need to make sure `clang` is installed on your computer. If it isn't available in your `PATH` (meaning `where.exe clang` returns an error), then you either need to add the directory it is in to your PATH, or specify the full path to it (`C:\foo\bar\clang.exe`) in the settings for `linter-clang`.

**Comment by BreederBai** [comment]
@Arcanemagus  This is my path to clang, i did not really install before
![image](https://user-images.githubusercontent.com/27894314/30101624-a0b1f300-931f-11e7-88d5-57ef1884c10f.png)
This is my setting
![image](https://user-images.githubusercontent.com/27894314/30101644-b76d409a-931f-11e7-8d40-53cfa5417a7e.png)
This is the case after the setting. The situation seems to have improved, but there is still an incorrect place
![image](https://user-images.githubusercontent.com/27894314/30101704-e8986ba4-931f-11e7-9768-a2672fe7463d.png)

**Comment by Arcanemagus** [comment]
Okay, so now that you have LLVM installed and the path set in the settings, run through the debugging steps outlined above in https://github.com/AtomLinter/linter-clang/issues/220#issuecomment-326346796.

(The errors you show in the console there have nothing to do with this package.)

**Comment by BreederBai** [comment]
@Arcanemagus When I run ATOM, there is an error
![tim 20170907100944](https://user-images.githubusercontent.com/27894314/30142970-07054eb8-93b6-11e7-879c-bc28dcdd332f.png)

**Comment by Arcanemagus** [comment]
Hmmm, that means it's taking longer than 10 seconds to run, can you try on a small file to make sure it's working at all?

**Comment by BreederBai** [comment]
@Arcanemagus when I try on a small file,It's ok.But it does not recognize some specific type.such as “sbit","idata".When I use the Keil4, it does not recognize some the IDE-provided header files, such as”#include <intrins.h>“
![image](https://user-images.githubusercontent.com/27894314/30193583-7f97e758-9480-11e7-82d4-442a8ae88fd2.png)
![image](https://user-images.githubusercontent.com/27894314/30193587-86f6f124-9480-11e7-82ba-02ebf4c55639.png)
![image](https://user-images.githubusercontent.com/27894314/30193598-9ac67a12-9480-11e7-9a62-b1d09a344e81.png)
![image](https://user-images.githubusercontent.com/27894314/30193611-af0adfcc-9480-11e7-93d7-45d81d1662f2.png)

**Comment by BreederBai** [comment]
@Arcanemagus  when I try on project ardupilot. "AP_HAL/AP_HAL.h" is in my project.
![image](https://user-images.githubusercontent.com/27894314/30193893-8e30fab4-9482-11e7-904f-4a70ae966979.png)
![image](https://user-images.githubusercontent.com/27894314/30194014-4a359ecc-9483-11e7-80f3-f5aed6360f1a.png)
![image](https://user-images.githubusercontent.com/27894314/30194029-57e6e3dc-9483-11e7-9007-8b4b61863a00.png)
![image](https://user-images.githubusercontent.com/27894314/30194034-67187988-9483-11e7-81fd-12bb4902bc3d.png)
![image](https://user-images.githubusercontent.com/27894314/30194056-7cadd266-9483-11e7-8d1b-269e4d61a562.png)

**Comment by BreederBai** [comment]
@Arcanemagus  
I place a breakpoint, saving a file :
![image](https://user-images.githubusercontent.com/27894314/30195340-725e204c-948b-11e7-8319-b244b46ead35.png)

**Comment by Arcanemagus** [comment]
@BreederBai Your "Keil4" types not found issue likely needs to be solved by fixing your include paths using a [`.clang_complete`](https://github.com/AtomLinter/linter-clang#clang_complete) file.

Your last comment (where you placed a breakpoint):
Does `D:\code\V3.5\20170818\libraries\AC_Fence\AP_HAL\AP_HAL.h` exist? I'm _guessing_ that that is a checkout of [this repo](https://github.com/ArduPilot/ardupilot/tree/d61705ee51c77b3f5d5cfa00d98d4d2e8c5aa3ef/libraries) which means that `AP_HAL` is a subdirectory of `libraries`, not `AC_Fence`. I'm guessing the simplest solution is similar to above: Create a `.clang_complete` file saying that `D:\code\V3.5\20170818\libraries` is an include path.

----

Since it looks like there isn't actually anything wrong with the package here I'm going to close the issue, feel free to keep posting though and I'll try to help, I don't actually use this package myself though.

**Comment by BreederBai** [comment]
@Arcanemagus  I need to put “.clang_complete” in which path

**Comment by Arcanemagus** [comment]
I believe it goes in the root of your project, this is getting beyond where I have detailed experience though so I'm somewhat guessing.
