### ISSUE TITLE
Linter-clang not linting project correctly

### ISSUE THREAD

**Issue by mkschleg** [AtomLinter/linter-clang#221]
This project was working a few weeks ago, but suddenly in my larger projects it has decided I have an obscene amount of errors and warnings without listing them and it doesn't even catch obvious errors. I'm not sure what is happening or how to debug as there are no errors in the developer window being shown.

Any help would be appreciated as this is a major tool for my workflow in atom.

The below image shows a lot of errors in the bottom left corner but nothing pulls up when clicked and nothing is in the pull up drawer when forced open. (This code compiles and runs jsyk)

<img width="1680" alt="screen shot 2017-08-30 at 1 11 39 pm" src="https://user-images.githubusercontent.com/16140693/29890428-cd75524c-8d84-11e7-8aa4-3888a5e9bd4f.png">

The below image shows the same # of errors and warnings, but I removed the semi-colon from line 102. The linter doesn't acknowledge this is an error.

<img width="1680" alt="screen shot 2017-08-30 at 1 12 37 pm" src="https://user-images.githubusercontent.com/16140693/29890472-ed498322-8d84-11e7-9e0d-e7e8ced1cd8a.png">

Again this package is working on other less complicated projects.

Thank you again.

**Comment by Arcanemagus** [comment]
The number of errors seems... excessive. By default though that is project wide, so any file you have open, plus potentially ones you don't have open could be contributing to that count. Without knowing anything about the messages being shown it's hard to know whether that is indicative of a bug, or to be expected.

As to why it isn't showing the expected results... if you open Atom's Developer Tools, find the files for this package and place a breakpoint here:

https://github.com/AtomLinter/linter-clang/blob/47ae300f6f19f671c98ada0b377e5c5e54a22279/lib/main.js#L257

Are you seeing expected results in the contents of `output`?

There are two possibilities here:
* It is returning before even running `clang`
* It's failing to parse the results from `clang`

**Comment by mkschleg** [comment]
Hm. Odd. Apparently there was a broken symlink with one of the libraries I was using. Any way this fixed the issue. Didn't know about breakpoints in Atom as I haven't dug to deep into how it works. Thanks for the help! I'm going to close this issue now.
