### ISSUE TITLE
linter does not work when Tree Sitter Parsers are enabled

### ISSUE THREAD

**Issue by tsoj** [AtomLinter/linter-clang#243]
When I enable the experimental tree sitter parser (https://github.com/atom/atom/pull/16299) the linter does not work (shows no errors where errors are).
I changed this line https://github.com/AtomLinter/linter-clang/blob/ae7b10e80ba94e7547cfd84643c6f70a383f6672/lib/main.js#L132 to this `grammarScopes: ['source.c', 'source.cpp', 'source.objc', 'source.objcpp', 'c', 'cpp', 'objc', 'objcpp'],` and it worked.

**Comment by Arcanemagus** [comment]
This scope change was reverted in Atom, either make sure you are on the current beta version, disable Tree-sitter, or wait for the reversion to hit stable.

Thanks for taking the time to file an issue!
