### ISSUE TITLE
Value of 'language' is an issue for clang 3.0

### ISSUE THREAD

**Issue by nickvanderstel** [AtomLinter/linter-clang#27]
The value of 'language' for a c file is 'c -std=c11'. This causes clang 3.0 to throw "error: invalid value 'c11' in '-std=c11'' (I notice it supports c89 but not c11).

Is there a reason the standard is defined? Maybe that should be configurable.

**Comment by Snake231088** [comment]
I removed -std=c11 try and reopen issue if the error persist
