### ISSUE TITLE
Default c++11 mode makes user specified standard flags useless (e.g. -std=c++1y)

### ISSUE THREAD

**Issue by wanderer2** [AtomLinter/linter-clang#28]
Title pretty much explains the problem. I can not make the package use the flag -std=c++1y. When I add this flag, the executed command gets the flag "-std=c++11 -std=c++1y", and clang uses the first. The issue can be resolved either by not setting a default std flag, or giving it as the last flag.

**Comment by Snake231088** [comment]
I put -std=c++11 like cpp flag so you can change it. In addition now you can specify more flag split from blank space.
Try this fix and reopen an issue if the problem persist
