### ISSUE TITLE
Clang fails to locate neighboring header files while in subdirectories

### ISSUE THREAD

**Issue by 0----0** [AtomLinter/linter-clang#30]
No matter how deep you are in a directory tree, clang will only have the root project directory in the include path.  My expected behavior is that clang should always have the directory of the file you are currently processing in its include path.

Reproduction:

1. Create an empty folder and open it in Atom.
2. Create a subdirectory named subdir.
3. Add files named "sub.hpp" and "sub.cpp" to the subdirectory.
4. Open sub.cpp and type in ```#include "sub.hpp"```.

This will produce an error stating ```'sub.hpp' file not found```.  Example shown below.
![Image of problem and directory tree](http://i.imgur.com/8gm8vaW.png)

In this example, I also determine that the problem does not affect files in the root project directory.
![Works fine](http://i.imgur.com/BVNbZTL.png)

**Comment by Snake231088** [comment]
I think i've fix it...try and if the problem persists reopen issue
