### ISSUE TITLE
Make red underline start at the location of the error

### ISSUE THREAD

**Issue by 0----0** [AtomLinter/linter-clang#34]
For every error detected by the clang linter, it will provide a red underline that covers the entire line which the error occurred on.  This makes visually identifying the cause of the error more difficult by providing less immediate information about the problematic piece of code.
![Which one of these did I forget to include?](http://i.imgur.com/8Yoj5so.png)

Clang's error output includes not only a line # but a column # indicating the location of the error more precisely.  AtomLinter provides functionality allowing you to specify a column for the start of the error, but this functionality is unused in linter-clang.  By providing the `col` regex value in the error match, such as with
```coffeescript
':(?<line>\\d+):(?<col>\\d+): .*((?<error>error)|(?<warning>warning)): (?<message>.*)'
```
we instead get
![Ah, that one.](http://i.imgur.com/zmHLRH6.png)
which mitigates the problem somewhat.

I think it is unlikely that it is possible to make the underline only affect the exact area of the line which is problematic, because of the way clang works, but if that's possible, it would be better.

**Comment by m-bra** [comment]
I think the option --caret-diagnostics does that, but I am not 100% sure.
The [manual](http://clang.llvm.org/docs/UsersManual.html#formatting-of-diagnostics) says that clang will print the range of the error, however, the example given does not fit to the explanation, so I may not have understood correctly.

**Comment by 0----0** [comment]
Thanks for the link.  The manual is very interesting.  Caret diagnostics certainly do seem to give range information, but I'm not sure we'd be able to parse it easily.  They're currently explicitly disabled.

Scrolling through the manual, I spotted `-fdiagnostics-print-source-range-info`, which seems like it'd be exactly what we want.  I'll have to test it more - it doesn't seem to give ranges in all situations, even when caret diagnostics give a proper range, such as with an undeclared identifier.

**Comment by m-bra** [comment]
Yeah but just because they are disabled in the code it does not mean you can change that :smile: 
Only the code in linter-clang.coffee is affected by the output of clang, and currently only the @regex member cares about the format of the output -> that means, if you change the regex appropriatley (which should not be too bad), you can enable caret diagnostics. Just for the clue.

**Comment by m-bra** [comment]
Okay, made PR, works. However, if clang gives just a *point* of error, the Linter package will continue the line till the end. This is an issue of the Linter package.
