### ISSUE TITLE
Add dependency 'Linter'?

### ISSUE THREAD

**Issue by m-bra** [AtomLinter/linter-clang#37]
Since this package needs the package to work properly, doesn't it make sense to add 'Linter' as a dependency so that it will be downloaded automatically? This could save a lot of pain (I forgot to download Linter when I first used linter-clang, too)

**Comment by Snake231088** [comment]
I think it's a good idea...i'll add the linter dep in package.json!

**Comment by m-bra** [comment]
I already pushed that, will merge with my PR
