### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/<user>/.config/google-chrome/SingletonCookie'

### ISSUE THREAD

**Issue by C0urante** [AtomLinter/linter-clang#42]
[Enter steps to reproduce below:]

1. Have at least one Google Chrome window currently open.
2. Run Atom (from command line or otherwise).
3. Attempt to use linter-clang.

**Atom Version**: 0.176.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [linter-clang](https://github.com/AtomLinter/linter-clang) package, v2.22.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/<user>/.config/google-chrome/SingletonCookie'

```
At /usr/share/atom/resources/atom/common/lib/asar.js:52

Error: ENOENT, no such file or directory '/home/<user>/.config/google-chrome/SingletonCookie'
  at Error (native)
  at fs.statSync (fs.js:726:18)
  at Object.fs.statSync (/usr/share/atom/resources/atom/common/lib/asar.js:155:14)
  at searchDirectory (/home/<user>/.atom/packages/linter-clang/lib/linter-clang.coffee:94:19)
  at searchDirectory (/home/<user>/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at searchDirectory (/home/<user>/.atom/packages/linter-clang/lib/linter-clang.coffee:96:11)
  at LinterClang.lintFile (/home/<user>/.atom/packages/linter-clang/lib/linter-clang.coffee:120:5)
  at /home/<user>/.atom/packages/linter/lib/linter-view.coffee:139:18
  at Array.forEach (native)
  at /home/<user>/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:11.3 application:new-file (atom-pane.pane.active.with-minimap)
  2x -0:08.1 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.1 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:06.1 snippets:expand (atom-text-editor.editor.is-focused)
     -0:06.1 editor:indent (atom-text-editor.editor.is-focused)
  4x -0:05.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.6 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/home/<user>/GitHub"
  },
  "linter-clang": {
    "clangDefaultCFlags": "-Wall -Wextra --pedantic -std=c99"
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.10.1
linter-clang, v2.22.0
linter-javac, v0.1.3
linter-pylint, v0.2.0
minimap, v3.5.6
monokai, v0.11.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by m-bra** [comment]
Can you open in dev mode, reproduce, turn on `verboseDebug` in the linter-clang settings, and show us the contents of the console?
The linter is searching for `.linter-clang-includes` in the project path recursively, so it would be useful to see how it got to open a non-existing file (look at the `searchDirectory`'s in the backtrace).
I think the issue is that if you have no path open (as a "project"), linter-clang will still ask for it and atom will just return `~`, which will make linter-clang  search the whole home directory *recursively*, which is generally bad.

**Comment by m-bra** [comment]
I think this is the same bug which cause #44
