### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mensinda** [AtomLinter/linter-clang#43]
Trying to install linter-clang results in following error:
```
 $ PYTHON=python2 apm install linter-clang

> runas@1.1.0 install /tmp/apm-install-dir-115030-16080-zsuyhb/node_modules/linter-clang/node_modules/clang-flags/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-115030-16080-zsuyhb/node_modules/linter-clang/node_modules/clang-flags/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:88: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-115030-16080-zsuyhb/node_modules/linter-clang/node_modules/clang-flags/node_modules/pathwatcher/node_modules/runas/build'

In file included from ../src/main.cc:1:0:
../../nan/nan.h:623:19: error: ‘NanNew’ declared as an ‘inline’ variable
       v8::String::ExternalAsciiStringResource *resource) {
                   ^
../../nan/nan.h:623:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
../../nan/nan.h:623:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
../../nan/nan.h:617:36: note: previous declaration ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
   NAN_INLINE v8::Local<v8::String> NanNew(
                                    ^
../../nan/nan.h:623:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
       v8::String::ExternalAsciiStringResource *resource) {
       ^
../../nan/nan.h:623:48: error: ‘resource’ was not declared in this scope
       v8::String::ExternalAsciiStringResource *resource) {
                                                ^
../../nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
../../nan/nan.h:1993:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
   if (str->IsExternalAscii()) {
            ^
../../nan/nan.h:1994:23: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
     const v8::String::ExternalAsciiStringResource* ext;
                       ^
../../nan/nan.h:1995:5: error: ‘ext’ was not declared in this scope
     ext = str->GetExternalAsciiStringResource();
     ^
../../nan/nan.h:1995:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
     ext = str->GetExternalAsciiStringResource();
                ^
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.18.4-1-ARCH
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115030-16080-zsuyhb/node_modules/linter-clang/node_modules/clang-flags/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.18.4-1-ARCH
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/.apmrc" "--userconfig" "/home/daniel/.atom/.apmrc" "install" "/tmp/d-115030-16080-1ucsvxb/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! runas@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115030-16080-zsuyhb/npm-debug.log
```

I do not know if this is usefull but I get an nearly identical error with [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang/issues/34)

**Comment by m-bra** [comment]
Platform? atom version?
Try updating atom. If you're on linux, this does **not** happen automatically, just redownload [atom.deb](https://atom.io/download/deb)

**Comment by mensinda** [comment]
Sorry forgot the system information.

OS: Arch Linux 64 bit
I have updated atom anly 2 hours ago (version 0.176.0.r91.gb02d0e3-1)

Clang Version: 3.5.1
GCC Version: 4.9.2

My system default compiler is GCC.

**Comment by m-bra** [comment]
Ah, the clang-flags package is causing the issue, which is used by both packages. I think just reimplementing the package and removing the dependency from this package would kinda solve, since it is pretty trivial and dependencies are bad.

**Comment by m-bra** [comment]
Open the issue [here](https://github.com/Kev/clang-flags/issues)

**Comment by yandy** [comment]
+1

**Comment by jose-villegas** [comment]
I don't have clang-flags package install I'm getting some of these errors, here is the output
Platform: Win8.1

> runas@1.1.0 install C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas>node "C:\Users\Jose\AppData\Local\atom\app-0.177.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(389,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
  main.cc
  runas_win.cc
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(623): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v8::String' (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          C:\Users\Jose\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\include\v8.h(1809) : see declaration of 'v8::String'
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(623): error C2065: 'ExternalAsciiStringResource' : undeclared identifier (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(623): error C2065: 'resource' : undeclared identifier (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(623): error C2448: 'NanNew' : function-style initializer appears to be a function definition (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(672): warning C4244: 'return' : conversion from 'int64_t' to 'int', possible loss of data (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1993): error C2039: 'IsExternalAscii' : is not a member of 'v8::String' (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          C:\Users\Jose\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\include\v8.h(1809) : see declaration of 'v8::String'
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1994): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v8::String' (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          C:\Users\Jose\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\include\v8.h(1809) : see declaration of 'v8::String'
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1994): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1994): error C2143: syntax error : missing ';' before '*' (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1994): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1995): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1995): error C2039: 'GetExternalAsciiStringResource' : is not a member of 'v8::String' (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          C:\Users\Jose\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\include\v8.h(1809) : see declaration of 'v8::String'
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1996): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1996): error C2227: left of '->data' must point to class/struct/union/generic type (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          type is 'unknown-type'
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1997): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\nan\nan.h(1997): error C2227: left of '->length' must point to class/struct/union/generic type (..\src\main.cc) [C:\Users\Jose\AppData\Local\Temp\apm-install-dir-11515-5948-1myzce9\node_modules\linter-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]
          type is 'unknown-type'

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Jose\\AppData\\Local\\atom\\app-0.177.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Jose\\AppData\\Local\\atom\\app-0.177.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Jose\\AppData\\Local\\atom\\app-0.177.0\\resources\\app\\apm\\.apmrc" "--userconfig" "C:\\Users\\Jose\\.atom\\.apmrc" "install" "C:\\Users\\Jose\\AppData\\Local\\Temp\\d-11515-5948-1vshn7h\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! runas@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by mensinda** [comment]
It looks like we have nearly the same problem with [pathwatcher](https://github.com/Kev/clang-flags/issues/6).

You can try to clone clang-flags and change the required pathwatcher version to `3.1.0` (in package.json). Then clone linter-clang into another directory and change the in package.json the line
```
"clang-flags": "git://github.com/wanderer2/clang-flags.git",
```
to
```
"clang-flags": "<your clang-flags path>",
```

and run `apm install .` and `apm ln`

This worked at least for me.

**Comment by jose-villegas** [comment]
Hey!, that worked thanks for the help man
