### ISSUE TITLE
Silently ignoring unfound header files

### ISSUE THREAD

**Issue by nickvanderstel** [AtomLinter/linter-clang#50]
Previously, a missing header file would be marked as an error. Now it seems they are not being handled properly. When a header is not in the configured path, linter-clang will not show any issues. However, in dev mode I will see: 'clang: stderr ... fatal error: ... file not found' in the console. In standard mode, linter does not report anything.

**Comment by m-bra** [comment]
This is because of #13: errors from other files should be shown. However, in this case, they should be shown as error. Can you give the console output in dev mode (and verboseDebug option set to true in linter clang settings)

**Comment by m-bra** [comment]
The problem was that clang did not parse fatal errors. Fixed that. Update and then response or close, please.

**Comment by Snake231088** [comment]
I've updated new release!test and then response or close!

**Comment by nickvanderstel** [comment]
Working fine now, thanks!
