### ISSUE TITLE
Atom hangs because of this package

### ISSUE THREAD

**Issue by EliaGeretto** [AtomLinter/linter-clang#52]
When I try to open a C++ file from the tree-view in Atom, the program hangs. No error message is displayed, after some seconds a popup appears telling me that Atom is not responding.

I was able to reproduce the problem only on my laptop. I have tried to reinstall Atom deleting the .atom folder in my home directory.

I tried to disable my packages one by one and the result was that the program hangs only when both the "linter" and the "linter-clang" package are enabled. I've tried also to install only those two packages and I was able to reproduce the problem.

I tried to install another linter package, "linter-csslint", and there is no problem in linting CSS files so I deduced that the problem was related to this package.

If I try to open a file from command line, instead that clicking on the TreeView, everything works perfectly.

The problem was not present on previous versions of Atom, it started with Atom 0.181.

I'm on Arch Linux, kernel 3.18.6, clang 3.5.1.
I installed Atom with an AUR package called "atom-editor-bin".

I doubt that the problem is directly caused by this package but I have no clue on how to resolve it, ask for any other information you may need.

**Comment by EliaGeretto** [comment]
I realized that if I open a C++ file from terminal and then I open another C++ file from the TreeView everything works fine in both package. It seems it's something related to the phase in which the package is loaded.

**Comment by EliaGeretto** [comment]
Issue still present in 0.182.0.

**Comment by m-bra** [comment]
I think this is most likely a problem with recursive searching. The linter packages searches the whole directory recursively for `.linter-clang-includes` (see readme). I did not experience performance issues with that. However this is an unresolved problem for really big project directories (Is your directory big?).

**Comment by m-bra** [comment]
One solution would be to enable the user to turn recursive searching off and only specifiy some `.linter-clang-includes`. (If you don't know what they are for, check the readme of this project).

**Comment by m-bra** [comment]
I will work on this if I have the time.

**Comment by EliaGeretto** [comment]
The issue is present when I open atom from terminal while I am in my home directory or in a higher level. If I enter in one of the subdirectories the problem is not present. Probably you're right.

Thank you.

**Comment by phord** [comment]
In my case (today) the hang was forever because my project has a recursive symlink.  So project/root/home -> /home, for example, and project/root/home/phord/project/root/home/phord/project/root/home... does too.

I removed the recursive symlink but something else seems to be tricking it up similarly.  I'll have to disable the package until #54 is resolved.

**Comment by k2b6s9j** [comment]
We are no longer searching recursively. This was caused by the .linter-clang-include file feature, which I have removed in this major rewrite. Please transition to a .clang_complete as this will be supported in the next minor version.
