### ISSUE TITLE
Linter clang doesn't work

### ISSUE THREAD

**Issue by arcanis** [AtomLinter/linter-clang#53]
I've just installed it on Atom Ubuntu, and it really doesn't work (it does nothing).

I've try to use the devtools to debug it, but I haven't figured out what's wrong : it gets into the lintFile function, but the Linter plugin display "null returned" everytime. I've launched the command in the terminal, and it returns what it should return (including errors).

**Comment by m-bra** [comment]
Can you go into dev mode, turn the option for verbose debugging on (you should find it in the project settings), and copy and paste the console output? (Open console with `strg-shift-I` on PC)

**Comment by Kuxe** [comment]
I have this issue to. Console output after forcing linting with CTRL-K + CTRL-L:

>/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 command and arguments ["/usr/bin/clang++", "/tmp/AtomLinter11539-10950-1i43as1source.cpp/rendersystem.cpp"]
/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 null returned LinterClang {editor: TextEditor, language: "c++", cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src", subscriptions: CompositeDisposable, executionTimeout: 5000…} []
/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 null returned LinterClang {editor: TextEditor, language: "c++", cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src", subscriptions: CompositeDisposable, executionTimeout: 5000…} []
/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 null returned LinterClang {editor: TextEditor, language: "c++", cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src", subscriptions: CompositeDisposable, executionTimeout: 5000…} []
/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 null returned LinterClang {editor: TextEditor, language: "c++", cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src", subscriptions: CompositeDisposable, executionTimeout: 5000…}_statCache: Mapcmd: "/usr/bin/clang++"cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src"editor: TextEditorexecutionTimeout: 5000language: "c++"regex: "\/tmp\/AtomLinter11539\-10950\-1i43as1source\.cpp\/rendersystem\.cpp:(?<line>\d+):(?<col>\d+):({(?<lineStart>\d+):(?<colStart>\d+)\-(?<lineEnd>\d+):(?<colEnd>\d+)}.*:)? ((?<error>(?:fatal )?error)|(?<warning>warning)): (?<message>.*)"subscriptions: CompositeDisposable__proto__: ctor []

This is not an issue with other linters (tested csslint). It does lint <i>sometimes</i>, approx once out of 20 attempts with CTRL-K + CTRL-L so it seems to work at random, but in general the linting doesn't succeed.

**Comment by nitzpo** [comment]
Any news here?

**Comment by k2b6s9j** [comment]
Could you test for this issue with the latest version?

**Comment by k2b6s9j** [comment]
Since this ticket has grown stale and the plugin has since been rewritten I am closing this ticket. If the issue is still occurring please reopen this ticket.
