### ISSUE TITLE
Don't search recursively

### ISSUE THREAD

**Issue by m-bra** [AtomLinter/linter-clang#54]
Searching the whole project directory for the `.linter-clang-include` files recursively is a problem when te directory has many files because it slows down atom.
Possible fixes:
 * Let the package have a setting where the recursive search can be limited by 1) totally turning it off (e.g. only having one `.linter-clang-include`), 2) ignoring certain directories and/or 3) specifying a maximum depth level to search.
 * Don't search recursively at all - enter at the first `.linter-clang-include` in the root directory and if the user wants to have more of those files they can specfigy those in the `.linter-clang-include` file.  
For example we have `.linter-clang-include` at the root dir and one in a directory `foo` and one in a directory `foo/bar/`.   
Now, in the file in the root dir we tell linter-clang to load the file inside `foo`, and in the file inside `foo` we tell linter-clang to load the file inside `bar` (which is a relative path).

The first fix is easier, the second fix is a bit harder but more efficient.

Related to #52

**Comment by aaronpuchert** [comment]
The second fix seems like the way to go, but having at most one `.linter-clang-include` might be sufficient as well. Do we have a case where multiple `.linter-clang-include` files are necessary?

**Comment by k2b6s9j** [comment]
Why not make recursive search a user configuration option?

**Comment by maxbrunsfeld** [comment]
Maybe the locations of the `.linter-clang-include` files should at least be cached. Just for another data point: in my project, I have one `.linter-clang-include` file at the root, but searching for that file takes about 75ms every time the file is linted. This freezes the UI for multiple animation frames.

**Comment by Luthaf** [comment]
I really would like to have this resolve, this make the clang linter totally unusable for me, as it looks from all the files in my `build` folder, which take up to 3s at each lint. A simple way to work around this would be to have an `ignore-path` option somewhere.

**Comment by k2b6s9j** [comment]
We are no longer searching recursively. This was caused by the `.linter-clang-include` file feature, which I have removed in this major rewrite. Please transition to a `.clang_complete` as this will be supported in the next minor version.
