### ISSUE TITLE
EACCES, unlink '...'

### ISSUE THREAD

**Issue by Fr0zen1** [AtomLinter/linter-clang#55]
Hello there, I get the following error when updating linter-clang.
EACCES, unlink '/home/USERNAME/.atom/packages/linter-clang/.npmignore'

I have recently updated Atom and this issue has come up. Thank you

Update: So I suspected it to be a perm problem and granted it permission and it updated but now I get 'Make sure clang++ is installed and on your PATH'. And I have '/usr/include/clang/3.5/include' in the PATH.

**Comment by k2b6s9j** [comment]
This was not a perm problem. This was an issue with the directory of the package was laid out, if you have this issue after the rewrite is merged in please tell me.

**Comment by gmish27** [comment]
@kepler0 I'm facing this issue now. Can you suggest a workaround? 
ATOM 1.4.0
linter-flake8 1.9.3

**Comment by kepler0** [comment]
@gmish27 I'm afraid I can't help with linter-flake8. You should file an issue on that repository and refer back to this issue.
