### ISSUE TITLE
"Error reading" Problems

### ISSUE THREAD

**Issue by hsidky** [AtomLinter/linter-clang#56]
Hello, 

Linter-clang has been working quite sporadically lately so I put Atom in dev mode to see what's going on. It seems that 4 in 5 attempts to lint a file results in an "Error reading..." error, and only works periodically. 

Here's the command that's running:

clang: stderr  "/usr/lib/llvm-3.5/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -main-file-name MoveTests.cpp -mrelocation-model static -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.24.90 -v -dwarf-column-info -resource-dir /usr/lib/llvm-3.5/bin/../lib/clang/3.5.0 -I /redacted/test -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/include/clang/3.5.0/include/ -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.5/bin/../lib/clang/3.5.0/include -internal-externc-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /redacted/test -ferror-limit 0 -fmessage-length 0 -fdiagnostics-print-source-range-info -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fno-caret-diagnostics -fno-diagnostics-fixit-info -fdiagnostics-show-option -x c++ /tmp/AtomLinter115213-15533-1wrlr7tsource.cpp/MoveTests.cpp

then there are a bunch of "null returned" 

lang: stderr clang -cc1 version 3.5.0 based upon LLVM 3.5.0 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9"
ignoring duplicate directory "/usr/include/clang/3.5.0/include"
#include "..." search starts here:
#include <...> search starts here:
 /redacted/test
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward
 /usr/include/clang/3.5.0/include
 /usr/local/include
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
error: error reading '/tmp/AtomLinter115213-15533-1wrlr7tsource.cpp/MoveTests.cpp'

Any thoughts on why this may be happening? Thanks!

**Comment by Kuxe** [comment]
I'm not sure how to acquire those logfiles you have, so I can't compare my logs with yours - but we have in common some output similar to
`/tmp/AtomLinter115213-15533-1wrlr7tsource.cpp/MoveTests.cpp`
and the bunch of "null returned".

My logs:
>command and arguments ["clang", "/tmp/AtomLinter11539-5999->9f6f3gsource.cpp/rendersystem.cpp"]
>/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 null returned LinterClang {editor: Object, >language: "c++", cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src", subscriptions: >CompositeDisposable, executionTimeout: 5000…} []
>/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 null returned LinterClang {editor: Object, >language: "c++", cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src", subscriptions: >CompositeDisposable, executionTimeout: 5000…} []
>/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 null returned LinterClang {editor: Object, >language: "c++", cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src", subscriptions: >CompositeDisposable, executionTimeout: 5000…} []
>/home/kuxe/.atom/packages/linter/lib/utils.coffee:11 null returned LinterClang {editor: Object, >language: "c++", cwd: "/home/kuxe/programming/gitrepos/swordbow-magic/src", subscriptions: >CompositeDisposable, executionTimeout: 5000…} []

I have no idea what to make out of these logfiles... I did notice that there's no rendersystem.cpp inside `/tmp/AtomLinter11539-5999-9f6f3gsource.cpp/rendersystem.cpp` when I check that folder (MoveTests.cpp in your case). It seems to be that clang expects rendersystem.cpp to be there, but it isn't.. So that leads me to think that this might be some permission issues with /tmp/. I don't know what to do about that though.

But then I don't know if rendersystem.cpp should be within /tmp/AtomLinter11539-5999-9f6f3gsource.cpp/ in the first place :)

**Comment by k2b6s9j** [comment]
The issue here has to due with the on the fly linting issues, caused by the complete override this package does with it's API. We are currently rewriting this for the [new API](https://github.com/AtomLinter/linter-plus). With the new API issues like this will fly out the window.

**Comment by k2b6s9j** [comment]
Could you please test this with the latest version?

**Comment by k2b6s9j** [comment]
Seeing as this ticket has grown stale and the linter has since been rewritten I am closing this ticket. If the issue is still occurring feel free to reopen this ticket.
