### ISSUE TITLE
linter-clang Organization Expansion

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinter/linter-clang#62]
It appears that this package could do better if @hd-deman expanded the team to the repo's most frequent contributors. I could be totally out of line here, but I'd rather have a larger team than infrequent pull requests being merged.

**Comment by TakenPilot** [comment]
+1

**Comment by hd-deman** [comment]
No problem, ask for and I will add you to the team

**Comment by k2b6s9j** [comment]
@m-bra, want in?
