### ISSUE TITLE
Multiple root support

### ISSUE THREAD

**Issue by randomstuff** [AtomLinter/linter-clang#86]
When multiple roots are used, only the first one is used for `.linter-clang-includes` and friends (`projectPath = atom.project.getPaths()[0]`). I guess I'd expect to use the `.linter-clang-*` for the root of the linted file.

**Comment by k2b6s9j** [comment]
A major rewrite for linter-clang is about to be released, alongside the major Linter rewrite. In the major rewrite for linter-clang I am redoing the way includes are handled like this.

**Comment by randomstuff** [comment]
OK, great! If anyone's interested, in the meanwhile, this diff should be fine:

    -projectPath = atom.project.getPaths()[0]
    +projectPath = (p for p in atom.project.getPaths() when (@cwd+"/").startsWith(p+"/"))[0]

**Comment by k2b6s9j** [comment]
`.linter-clang-includes` support has been removed for `.clang_complete` files for the near future.
