### ISSUE TITLE
Firewall/proxy issue

### ISSUE THREAD

**Issue by FatManiac** [AtomLinter/linter-clang#87]
Hi,
my proxy/firewall is blocking the connection to install your package, can you switch from git:// schema to https:// ?

**Comment by k2b6s9j** [comment]
Are you able to install other packages? Or is it just this package that is causing you issue?

**Comment by FatManiac** [comment]
i can install other package, i just can't install package from AtomLinter

**Comment by FatManiac** [comment]
up

**Comment by abinashmeher999** [comment]
I am having the same issue.

**Comment by k2b6s9j** [comment]
I'm sorry about that. The previous maintainer did not understand how Node modules worked and created an unforeseen issue.
