### ISSUE TITLE
#pragma once in main file

### ISSUE THREAD

**Issue by jhasse** [AtomLinter/linter-clang#88]
I'm getting `#pragma once in main file` when viewing any header file with `#pragma once`. Is there a way to disable this? (clang v3.4)

**Comment by k2b6s9j** [comment]
Okay. I'm almost sure this is still an issue, but could you please test this with the latest version?

**Comment by sailorswift** [comment]
I have the same issue on the newest version.

**Comment by k2b6s9j** [comment]
Okay. Thanks for confirming this issue still exists. I will investigate to see what can be done.

**Comment by thomassuckow** [comment]
I would probably either tell clang to make precompiled headers (if possible) or just use a regex in the plugin to filter out that message on non-c/cpp files. It is erroneous for headers.

**Comment by sailorswift** [comment]
:+1: to just ignoring the error on header files.

**Comment by lbguilherme** [comment]
Any progress on this?

**Comment by kepler0** [comment]
I haven't done anything with this yet. A Pull Request would be appreciated.

**Comment by Joeasaurus** [comment]
+1 please!

**Comment by jplatte** [comment]
This warning has its own flag and can be disabled with the `no-` counterpart. So, right now you can work around this issue by putting `-Wno-pragma-once-outside-header` in your projects `.clang_complete`.

Likewise, it could be fixed here by adding that flag to the default C and/or C++ flags.
