### ISSUE TITLE
Not working on the fly

### ISSUE THREAD

**Issue by Kamairo** [AtomLinter/linter-clang#91]
I cannot get linter-clang to work on-the-fly.
If type some wrong syntax in a .cpp file and close and reopen atom, the errors are correctly underlined, but this does not work on-the-fly. Saving the file also does not help, I have to close and reopen atom.

I am on Linux Mint 17.1 64-bit, clang 3.4, kernel 3.13.

I also tested linter-cpplint to check if it's a problem with this package or linter itself. linter-cpplint is working fine on-the-fly.

**Comment by k2b6s9j** [comment]
This package will not work on the fly, due to the compilation nature of clang.
