### ISSUE TITLE
"Clang Default Cpp Flags" seems not to be working

### ISSUE THREAD

**Issue by equal-l2** [AtomLinter/linter-clang#97]
Atom 1.0.3
linter 1.3.0
linter-clang 3.0.0
on Windows 8.1

"Clang Default Cpp Flags"　seems not to have any effect

**Comment by k2b6s9j** [comment]
I'm going to need some more information than this. Could you please tell me what the config value is, the expected behavior, and what actually happened?

**Comment by equal-l2** [comment]
Sorry, I misunderstood about the problem.

Through some more tests, I found that "Clang Default Cpp Flags" avtually works except some cases.

 I'll open new issue with appropriate title and more details.

**Comment by k2b6s9j** [comment]
Don't worry about it.
