### ISSUE TITLE
No project specific settings

### ISSUE THREAD

**Issue by csholmq** [AtomLinter/linter-clang#98]
With the new 3.0.0 release, .linter-clang-includes is no longer parsed and I am unable to include my build directory.

With multiple projects (and thus multiple build dirs) how am I suppose to handle that with a single include path?

**Comment by swaj** [comment]
This one is hitting me, too.

**Comment by k2b6s9j** [comment]
We are replacing project specific settings with .clang_complete files and
LLVM JSON Compilation Database files. Both of which are supported through
the clang-flags node package. Implementation will be finished at most by
the end of the week.

**Comment by k2b6s9j** [comment]
This will be in linter-clang version 3.1.0. Should be on APM real soon.

**Comment by k2b6s9j** [comment]
3.1.0 has been published. Please reopen this issue if you have problems.

**Comment by csholmq** [comment]
Works like a charm! Great work!

**Comment by k2b6s9j** [comment]
Awesome! That same file will work with [autocomplete-clang](https://atom.io/packages/autocomplete-clang) by the way...

**Comment by Kerosene2000** [comment]
Hum... why you didn't explain this somewhere ? On the README.md for example ? That will be cool for the new users :smile:
